name: CI

on:
  push:
    branches:
      - master
      - develop
      - 'feat/*'

env:
  NODE_VERSION: 12.x

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: yarn install --frozen-lockfile

      - run: yarn global add truffle

      - name: test contracts
        run: truffle test
